CinemaMovie/CinemaMovie/Models/Actor.cs
namespace CinemaMovie.Models
{
    public class Actor
    {
        public int Id { get; set; }
        public string Firstname { get; set; }  // имя актера
        public string Lastname { get; set; }  // фамилия актера
        public Movie Movie { get; set; } // связь один ко многим
        
    } 
}

CinemaMovie/CinemaMovie/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CinemaMovie.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaMovie.Controllers
{
    public class ActorController : Controller
    {
        private MoviesContext db;
        public ActorController(MoviesContext context)
        {
            db = context;
        }
        // GET: Actor
        public IActionResult Index()
        {
            ViewBag.actors = db.Actors.ToList();
            return View();
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Actor actor)
        {
            // добавляем информацию в базу данных
            db.Actors.Add(actor);
            // сохраняем в бд все изменения
            db.SaveChanges();
            return Redirect("/Home/Index");
        }
        [HttpGet] // метод редактирования
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Actor actor = await db.Actors.FirstOrDefaultAsync(p => p.Id == id);
                if (actor != null)
                    return View(actor);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Actor actor)
        {
            db.Actors.Update(actor);
            await db.SaveChangesAsync();
            return RedirectToAction("/Home/Index");
        }
        [HttpGet] // метод удаления
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Actor actor = await db.Actors.FirstOrDefaultAsync(p => p.Id == id);
                if (actor != null)
                    return View(actor);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Actor actor = await db.Actors.FirstOrDefaultAsync(p => p.Id == id);
                if (actor != null)
                {
                    db.Actors.Remove(actor);
                    await db.SaveChangesAsync();
                    return RedirectToAction("/Home/Index");
                }
            }
            return NotFound();
        }
    }
}

CinemaMovie/CinemaMovie/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CinemaMovie.Models;
using Microsoft.EntityFrameworkCore;

namespace CinemaMovie.Controllers
{
    public class HomeController : Controller
    {
        private MoviesContext db;
        public HomeController(MoviesContext context)
        {
           db  = context;
        }
        public IActionResult Index()
        {
            ViewBag.movies = db.Movies.ToList();
            return View();
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public string Add(Movie movie)
        {
            // добавляем информацию в базу данных
            db.Movies.Add(movie);
            // сохраняем в бд все изменения
            db.SaveChanges();
            return "---Спасибо---";
        }
        [HttpGet] // метод редактирования
        public async Task<IActionResult> Edit(int? id) 
        {
            if (id != null)
            {
                Movie movie = await db.Movies.FirstOrDefaultAsync(p => p.Id == id);
                if (movie != null)
                    return View(movie);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Movie movie)
        {
            db.Movies.Update(movie);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet] // метод удаления
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id) 
        {
            if (id != null)
            {
                Movie movie = await db.Movies.FirstOrDefaultAsync(p => p.Id == id);
                if (movie != null)
                    return View(movie);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Movie movie = await db.Movies.FirstOrDefaultAsync(p => p.Id == id);
                if (movie != null)
                {
                    db.Movies.Remove(movie);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
    public class HomeActorController : Controller
    {
        private MoviesContext db;
        public HomeActorController(MoviesContext context)
        {
            db = context;
        }
        [HttpGet]
        public ActionResult AddActor(string Name)
        {
            ViewBag.Actor = Name;
            return View();
        }
        [HttpPost]
        public string AddActor(Actor actor)
        {
            // добавляем информацию в базу данных
            db.Actors.Add(actor);
            // сохраняем в бд все изменения
            db.SaveChanges();
            return "---Спасибо---";
        }
        [HttpGet] // метод редактирования
        public async Task<IActionResult> EditActor(int? id)
        {
            if (id != null)
            {
                Actor actor = await db.Actors.FirstOrDefaultAsync(p => p.Id == id);
                if (actor != null)
                    return View(actor);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EditActor(Actor actor)
        {
            db.Actors.Update(actor);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet] // метод удаления
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDeleteActor(int? id)
        {
            if (id != null)
            {
                Actor actor = await db.Actors.FirstOrDefaultAsync(p => p.Id == id);
                if (actor != null)
                    return View(actor);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteActor(int? id)
        {
            if (id != null)
            {
                Actor actor = await db.Actors.FirstOrDefaultAsync(p => p.Id == id);
                if (actor != null)
                {
                    db.Actors.Remove(actor);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

}

CinemaMovie/CinemaMovie/Views/Actor/Add.cshtml
@{
    ViewData["Title"] = "Add";
}
<div>
    <h3>Добавление актёров в список</h3>
    <p>Для добавления заполните следующие поля:</p>
    <form method="post">
        <table>
            <tr>
                <td>Имя актёра:</td>
                <td><input type="text" name="Firstname" /> </td>
            </tr>
            <tr>
                <td>Фамилия актёра:</td>
                <td><input type="text" name="Lastname" /></td>
            </tr>
            <tr><td><input type="submit" value="Сохранить" /></td><td></td></tr>
        </table>
    </form>
</div>

CinemaMovie/CinemaMovie/Views/Actor/Delete.cshtml
@model CinemaMovie.Models.Actor
@{
    ViewData["Title"] = "Delete";
}
<div>
    <h3>"Удаленить актёра"</h3>
</div>
<div>
    <dl class="dl-horizontal">
        <dt>Имя актёра:</dt>
        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt>Фамилия актёра:</dt>
        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>
    </dl>
    <div>
        <form asp-controller="Actor" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

CinemaMovie/CinemaMovie/Views/Actor/Edit.cshtml
@model CinemaMovie.Models.Actor
@{
    ViewData["Title"] = "Edit";
}
<div>
    <h3>"Редактирование Имя и Фамилии актёра"</h3>
</div>
<form asp-action="EditActor" asp-controller="HomeActor" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Firstname" class="control-label">Имя актёра:</label>
        <input type="text" asp-for="Firstname" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Lastname" class="control-label">Фамилия актёра:</label>
        <input type="text" asp-for="Lastname" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

CinemaMovie/CinemaMovie/Views/Actor/Index.cshtml
@model IEnumerable<CinemaMovie.Models.Actor>
@{
    ViewData["Title"] = "Index";
}
    <div class="text-center">
        <h1 class="display-4">Actors Marvel</h1>
    </div>
<div class="col-lg-9">
    <ul>
        @foreach (var actor in ViewBag.actors)
        {
            <li>@actor.Firstname @actor.Lastname</li>
            <table>
                <tr>
                    <p><a asp-action="Edit" asp-controller="Actor" asp-route-id="@actor.Id">Изменить актера</a></p>
                    <p><a asp-action="Delete" asp-controller="Actor" asp-route-id="@actor.Id">Удалить актера</a></p>
                </tr>
            </table>
        }
    </ul>
</div>
<div>
    <table>
        <tr>
            <td><p><a href="/Actor/Add"><input type="submit" value="Добавить актера" /></a></p></td>
        </tr>
    </table>
</div>